import {ExperienceItem} from "../models";

export const experienceItems = [
  new ExperienceItem("Software Engineer AMTS", "MuleSoft", "Oct 2021", "now", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec finibus quis urna sit amet efficitur. Donec aliquam tellus sit amet enim consequat accumsan. Donec volutpat, lectus quis dictum iaculis, purus turpis interdum augue, eu consectetur lorem nunc in arcu. Sed facilisis laoreet quam, ut ullamcorper leo sagittis nec. Aliquam laoreet laoreet odio. Maecenas fringilla tellus in dui bibendum, in gravida augue maximus. Duis imperdiet justo dolor, nec ullamcorper dolor eleifend non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst. Nam non est orci. Sed accumsan elementum mauris finibus iaculis. Aliquam porttitor nisl vel nibh fermentum, non laoreet neque ornare. Sed dictum fringilla mauris vitae condimentum. Sed eget felis semper, interdum ipsum eu, elementum sapien.", "", "",),
  new ExperienceItem("Java Software Developer", "Epidata", "Apr 2020", "Oct 2021", "The focus of the role was on maintaining multiple Mulesoft's connectors, which involved performing various tasks such as resolving bugs and vulnerabilities, implementing new features, and developing new connectors. As part of the role, the team worked on developing connectors for various software platforms, including MongoDB, NetSuite, and others.", "", "",),
  new ExperienceItem("MTF & Munit Developer", "Epidata", "Oct 2018", "Apr 2020", "The role involved migrating tests of various Mulesoft connectors from Java (JUnit) to MTF, Mulesoft's own testing framework. The primary responsibility was to ensure a smooth transition and to ensure that existing test suites functioned correctly. Additionally, the job required collaborating with other Mulesoft teams to provide consultation and assistance in developing new tests for future connectors. The project involved working on some significant connectors like SAP, Salesforce, and Oracle EBS, among others, and ensuring that their testing frameworks were robust enough to detect issues before they appeared in production environments.", "", "")
];
export const educationItems = [
  new ExperienceItem("Licenciatura en Informática", "Universidad Nacional de Hurlingham", "Mar 2020", "now", "Other info", "https://unahur.edu.ar/es/licenciatura-en-informatica", ""),
  new ExperienceItem("Ingeniería en computación", "Universidad Nacional de Tres de Febrero", "Aug 2017", " Dec 2020 (unfinished)", "Other info", "https://www.untref.edu.ar/carrera/ingenieria-en-computacion", ""),
];

